<?xml version="1.0" encoding="UTF-16"?>
<!--
This file was generated by Altova MapForce 2020r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:grp="http://www.altova.com/Mapforce/grouping" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" exclude-result-prefixes="grp xs fn">
    <xsl:output method="xml" encoding="UTF-16" byte-order-mark="no" indent="yes" omit-xml-declaration="yes" />
    <xsl:function name="grp:MapToEDISalesOrderD365_var2_map_of_DefaultDimension">
        <xsl:param name="var1_cur" as="node()" />
        <xsl:for-each select="$var1_cur/DefaultDimension/Values/Value/Name">
            <xsl:sequence select="fn:string(.)" />
        </xsl:for-each>
    </xsl:function>
    <xsl:template match="/">
        <_salesOrder>
            <xsl:for-each select="X12_00401_850">
                <xsl:variable name="var55_DTM" as="node()*" select="DTM" />
                <xsl:variable name="var54_BEG" as="node()" select="BEG" />
                <xsl:variable name="var53_tokenize_regexp_of_BEG__" as="xs:string*">
                    <xsl:for-each select="$var54_BEG/BEG04">
                        <xsl:sequence select="tokenize(fn:string(.), replace('^', '(\.|\$|\^|\{|\[|\(|\||\)|\*|\+|\?|\\)', '\\$1'))" />
                    </xsl:for-each>
                </xsl:variable>
                <xsl:variable name="var48_resultof_filter" as="node()*">
                    <xsl:for-each select="$var55_DTM">
                        <xsl:variable name="var47_cur" as="node()" select="." />
                        <xsl:if test="fn:exists((./DTM02)[('064' = fn:string($var47_cur/DTM01))])">
                            <xsl:sequence select="." />
                        </xsl:if>
                    </xsl:for-each>
                </xsl:variable>
                <xsl:variable name="var49_resultof_any" as="xs:boolean" select="fn:exists($var48_resultof_filter)" />
                <xsl:variable name="var51_resultof_filter" as="node()*">
                    <xsl:for-each select="$var55_DTM">
                        <xsl:variable name="var50_cur" as="node()" select="." />
                        <xsl:if test="fn:exists((./DTM02)[('063' = fn:string($var50_cur/DTM01))])">
                            <xsl:sequence select="." />
                        </xsl:if>
                    </xsl:for-each>
                </xsl:variable>
                <xsl:variable name="var52_resultof_any" as="xs:boolean" select="fn:exists($var51_resultof_filter)" />
                <xsl:variable name="var31_test_any" as="node()?">
                    <xsl:if test="$var49_resultof_any">
                        <xsl:variable name="var30_map_of_DTM" as="xs:string*">
                            <xsl:for-each select="$var55_DTM">
                                <xsl:variable name="var29_cur" as="node()" select="." />
                                <xsl:for-each select="(./DTM02)[('064' = fn:string($var29_cur/DTM01))]">
                                    <xsl:variable name="var28___as_double" as="xs:double" select="xs:double(xs:decimal('2'))" />
                                    <xsl:variable name="var27_cur_as_string" as="xs:string" select="fn:string(.)" />
                                    <xsl:sequence select="fn:concat(fn:concat(fn:concat(fn:concat(fn:substring($var27_cur_as_string, xs:double(xs:decimal('5')), $var28___as_double), '-'), fn:substring($var27_cur_as_string, xs:double(xs:decimal('7')), $var28___as_double)), '-'), fn:substring($var27_cur_as_string, xs:double(xs:decimal('1')), xs:double(xs:decimal('4'))))" />
                                </xsl:for-each>
                            </xsl:for-each>
                        </xsl:variable>
                        <ShipStartDate>
                            <xsl:sequence select="xs:string(fn:string-join(for $x in $var30_map_of_DTM return xs:string($x), ' '))" />
                        </ShipStartDate>
                    </xsl:if>
                </xsl:variable>
                <xsl:variable name="var36_test_any" as="node()?">
                    <xsl:if test="$var49_resultof_any">
                        <xsl:variable name="var35_map_of_DTM" as="xs:string*">
                            <xsl:for-each select="$var55_DTM">
                                <xsl:variable name="var34_cur" as="node()" select="." />
                                <xsl:for-each select="(./DTM02)[('064' = fn:string($var34_cur/DTM01))]">
                                    <xsl:variable name="var33___as_double" as="xs:double" select="xs:double(xs:decimal('2'))" />
                                    <xsl:variable name="var32_cur_as_string" as="xs:string" select="fn:string(.)" />
                                    <xsl:sequence select="fn:concat(fn:concat(fn:concat(fn:concat(fn:substring($var32_cur_as_string, xs:double(xs:decimal('5')), $var33___as_double), '-'), fn:substring($var32_cur_as_string, xs:double(xs:decimal('7')), $var33___as_double)), '-'), fn:substring($var32_cur_as_string, xs:double(xs:decimal('1')), xs:double(xs:decimal('4'))))" />
                                </xsl:for-each>
                            </xsl:for-each>
                        </xsl:variable>
                        <RequestedShippingDate>
                            <xsl:sequence select="xs:string(fn:string-join(for $x in $var35_map_of_DTM return xs:string($x), ' '))" />
                        </RequestedShippingDate>
                    </xsl:if>
                </xsl:variable>
                <xsl:variable name="var41_test_any" as="node()?">
                    <xsl:if test="$var52_resultof_any">
                        <xsl:variable name="var40_map_of_DTM" as="xs:string*">
                            <xsl:for-each select="$var55_DTM">
                                <xsl:variable name="var39_cur" as="node()" select="." />
                                <xsl:for-each select="(./DTM02)[('063' = fn:string($var39_cur/DTM01))]">
                                    <xsl:variable name="var38___as_double" as="xs:double" select="xs:double(xs:decimal('2'))" />
                                    <xsl:variable name="var37_cur_as_string" as="xs:string" select="fn:string(.)" />
                                    <xsl:sequence select="fn:concat(fn:concat(fn:concat(fn:concat(fn:substring($var37_cur_as_string, xs:double(xs:decimal('5')), $var38___as_double), '-'), fn:substring($var37_cur_as_string, xs:double(xs:decimal('7')), $var38___as_double)), '-'), fn:substring($var37_cur_as_string, xs:double(xs:decimal('1')), xs:double(xs:decimal('4'))))" />
                                </xsl:for-each>
                            </xsl:for-each>
                        </xsl:variable>
                        <ShipByDate>
                            <xsl:sequence select="xs:string(fn:string-join(for $x in $var40_map_of_DTM return xs:string($x), ' '))" />
                        </ShipByDate>
                    </xsl:if>
                </xsl:variable>
                <xsl:variable name="var46_test_any" as="node()?">
                    <xsl:if test="$var52_resultof_any">
                        <xsl:variable name="var45_map_of_DTM" as="xs:string*">
                            <xsl:for-each select="$var55_DTM">
                                <xsl:variable name="var44_cur" as="node()" select="." />
                                <xsl:for-each select="(./DTM02)[('063' = fn:string($var44_cur/DTM01))]">
                                    <xsl:variable name="var43___as_double" as="xs:double" select="xs:double(xs:decimal('2'))" />
                                    <xsl:variable name="var42_cur_as_string" as="xs:string" select="fn:string(.)" />
                                    <xsl:sequence select="fn:concat(fn:concat(fn:concat(fn:concat(fn:substring($var42_cur_as_string, xs:double(xs:decimal('5')), $var43___as_double), '-'), fn:substring($var42_cur_as_string, xs:double(xs:decimal('7')), $var43___as_double)), '-'), fn:substring($var42_cur_as_string, xs:double(xs:decimal('1')), xs:double(xs:decimal('4'))))" />
                                </xsl:for-each>
                            </xsl:for-each>
                        </xsl:variable>
                        <RequestedReceiptDate>
                            <xsl:sequence select="xs:string(fn:string-join(for $x in $var45_map_of_DTM return xs:string($x), ' '))" />
                        </RequestedReceiptDate>
                    </xsl:if>
                </xsl:variable>
                <xsl:variable name="var26_let" as="node()*">
                    <SalesOrderNumber></SalesOrderNumber>
                    <OrderClassificationId>STANDALONE</OrderClassificationId>
                    <xsl:for-each select="(./N1Loop1)[(fn:upper-case(fn:string(N1/N101)) = 'ST')]">
                        <xsl:variable name="var21_create_N_Loop_" as="node()">
                            <N1Loop1>
                                <xsl:sequence select="(./@node(), ./node())" />
                            </N1Loop1>
                        </xsl:variable>
                        <xsl:for-each select="$var21_create_N_Loop_/N1/N104">
                            <DistributionCenterAccount>
                                <xsl:sequence select="fn:string(.)" />
                            </DistributionCenterAccount>
                        </xsl:for-each>
                    </xsl:for-each>
                    <xsl:variable name="var24_BEG__" as="node()" select="$var54_BEG/BEG05" />
                    <xsl:variable name="var23___as_double" as="xs:double" select="xs:double(xs:decimal('2'))" />
                    <xsl:variable name="var22_cur_as_string" as="xs:string" select="fn:string($var24_BEG__)" />
                    <OrderDate>
                        <xsl:sequence select="fn:concat(fn:concat(fn:concat(fn:concat(fn:substring($var22_cur_as_string, xs:double(xs:decimal('5')), $var23___as_double), '-'), fn:substring($var22_cur_as_string, xs:double(xs:decimal('7')), $var23___as_double)), '-'), fn:substring($var22_cur_as_string, xs:double(xs:decimal('1')), xs:double(xs:decimal('4'))))" />
                    </OrderDate>
                    <OrderingCustomerAccountNumber>AMA103</OrderingCustomerAccountNumber>
                    <InvoiceCustomerAccountNumber>AMA103</InvoiceCustomerAccountNumber>
                    <CurrencyCode>USD</CurrencyCode>
                    <CustomersOrderReference>
                        <xsl:sequence select="fn:string($var54_BEG/BEG03)" />
                    </CustomersOrderReference>
                    <xsl:for-each select="($var53_tokenize_regexp_of_BEG__)[(fn:position() = xs:integer('1'))]">
                        <deliveryModeCode>
                            <xsl:sequence select="." />
                        </deliveryModeCode>
                    </xsl:for-each>
                    <LanguageId>en-us</LanguageId>
                    <xsl:for-each select="($var53_tokenize_regexp_of_BEG__)[(fn:position() = xs:integer('2'))]">
                        <PaymentTermsName>
                            <xsl:sequence select="." />
                        </PaymentTermsName>
                    </xsl:for-each>
                    <xsl:for-each select="($var53_tokenize_regexp_of_BEG__)[(fn:position() = xs:integer('3'))]">
                        <CustomerPaymentMethodName>
                            <xsl:sequence select="." />
                        </CustomerPaymentMethodName>
                    </xsl:for-each>
                    <xsl:for-each select="($var53_tokenize_regexp_of_BEG__)[(fn:position() = xs:integer('4'))]">
                        <CustomerPaymentMethodSpecificationName>
                            <xsl:sequence select="." />
                        </CustomerPaymentMethodSpecificationName>
                    </xsl:for-each>
                    <xsl:sequence select="$var46_test_any" />
                    <SalesOrderOriginCode>EDI</SalesOrderOriginCode>
                    <xsl:sequence select="$var36_test_any" />
                    <OrderResponsiblePersonnelNumber>999777</OrderResponsiblePersonnelNumber>
                    <OrderTakerPersonnelNumber>999777</OrderTakerPersonnelNumber>
                    <xsl:sequence select="$var31_test_any" />
                    <xsl:sequence select="$var41_test_any" />
                    <xsl:for-each select="PO1Loop1">
                        <xsl:variable name="var25_PO_" as="node()" select="PO1" />
                        <SalesLinesList>
                            <xsl:for-each select="$var25_PO_/PO101">
                                <CustomersLineNumber>
                                    <xsl:sequence select="fn:string(.)" />
                                </CustomersLineNumber>
                            </xsl:for-each>
                            <xsl:for-each select="($var25_PO_/PO107)[fn:exists(($var25_PO_/PO106)[(fn:string(.) = 'VN')])]">
                                <ItemNumber>
                                    <xsl:sequence select="fn:string(.)" />
                                </ItemNumber>
                            </xsl:for-each>
                            <xsl:sequence select="$var46_test_any" />
                            <xsl:for-each select="$var25_PO_/PO104">
                                <SalesPrice>
                                    <xsl:sequence select="fn:string(.)" />
                                </SalesPrice>
                            </xsl:for-each>
                            <xsl:for-each select="$var25_PO_/PO102">
                                <OrderedSalesQuantity>
                                    <xsl:sequence select="fn:string(.)" />
                                </OrderedSalesQuantity>
                            </xsl:for-each>
                            <xsl:for-each select="$var25_PO_/PO103">
                                <SalesUnitSymbol>
                                    <xsl:sequence select="fn:string(.)" />
                                </SalesUnitSymbol>
                            </xsl:for-each>
                            <xsl:sequence select="$var36_test_any" />
                            <xsl:sequence select="$var31_test_any" />
                            <xsl:sequence select="$var41_test_any" />
                        </SalesLinesList>
                    </xsl:for-each>
                    <SalesLinesList>
                        <xsl:sequence select="()" />
                    </SalesLinesList>
                </xsl:variable>
                <xsl:variable name="var3_create_SalesHeadersList" as="node()">
                    <SalesHeadersList>
                        <xsl:sequence select="$var26_let" />
                    </SalesHeadersList>
                </xsl:variable>
                <xsl:for-each-group select="$var3_create_SalesHeadersList/SalesLinesList" group-by="grp:MapToEDISalesOrderD365_var2_map_of_DefaultDimension(.)">
                    <xsl:variable name="var19_resultof_grouping_key" as="xs:string" select="current-grouping-key()" />
                    <SalesHeadersList>
                        <xsl:variable name="var4_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var4_create_SalesHeadersList/SalesOrderNumber">
                            <SalesOrderNumber>
                                <xsl:sequence select="fn:string(.)" />
                            </SalesOrderNumber>
                        </xsl:for-each>
                        <xsl:variable name="var5_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var5_create_SalesHeadersList/OrderClassificationId">
                            <OrderClassificationId>
                                <xsl:sequence select="fn:string(.)" />
                            </OrderClassificationId>
                        </xsl:for-each>
                        <StoreCode>
                            <xsl:sequence select="$var19_resultof_grouping_key" />
                        </StoreCode>
                        <xsl:variable name="var6_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var6_create_SalesHeadersList/DistributionCenterAccount">
                            <DistributionCenterAccount>
                                <xsl:sequence select="fn:string(.)" />
                            </DistributionCenterAccount>
                        </xsl:for-each>
                        <xsl:variable name="var7_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var7_create_SalesHeadersList/OrderDate">
                            <OrderDate>
                                <xsl:sequence select="fn:string(.)" />
                            </OrderDate>
                        </xsl:for-each>
                        <xsl:variable name="var8_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var8_create_SalesHeadersList/OrderingCustomerAccountNumber">
                            <OrderingCustomerAccountNumber>
                                <xsl:sequence select="fn:string(.)" />
                            </OrderingCustomerAccountNumber>
                        </xsl:for-each>
                        <xsl:variable name="var9_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var9_create_SalesHeadersList/InvoiceCustomerAccountNumber">
                            <InvoiceCustomerAccountNumber>
                                <xsl:sequence select="fn:string(.)" />
                            </InvoiceCustomerAccountNumber>
                        </xsl:for-each>
                        <xsl:variable name="var10_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var10_create_SalesHeadersList/CustomersOrderReference">
                            <CustomersOrderReference>
                                <xsl:sequence select="fn:string(.)" />
                            </CustomersOrderReference>
                        </xsl:for-each>
                        <xsl:variable name="var11_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var11_create_SalesHeadersList/LanguageId">
                            <LanguageId>
                                <xsl:sequence select="fn:string(.)" />
                            </LanguageId>
                        </xsl:for-each>
                        <xsl:variable name="var12_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var12_create_SalesHeadersList/RequestedReceiptDate">
                            <RequestedReceiptDate>
                                <xsl:sequence select="fn:string(.)" />
                            </RequestedReceiptDate>
                        </xsl:for-each>
                        <xsl:variable name="var13_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var13_create_SalesHeadersList/SalesOrderOriginCode">
                            <SalesOrderOriginCode>
                                <xsl:sequence select="fn:string(.)" />
                            </SalesOrderOriginCode>
                        </xsl:for-each>
                        <xsl:variable name="var14_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var14_create_SalesHeadersList/RequestedShippingDate">
                            <RequestedShippingDate>
                                <xsl:sequence select="fn:string(.)" />
                            </RequestedShippingDate>
                        </xsl:for-each>
                        <xsl:variable name="var15_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var15_create_SalesHeadersList/ShipStartDate">
                            <ShipStartDate>
                                <xsl:sequence select="fn:string(.)" />
                            </ShipStartDate>
                        </xsl:for-each>
                        <xsl:variable name="var16_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var16_create_SalesHeadersList/ShipByDate">
                            <ShipByDate>
                                <xsl:sequence select="fn:string(.)" />
                            </ShipByDate>
                        </xsl:for-each>
                        <xsl:variable name="var17_create_SalesHeadersList" as="node()">
                            <SalesHeadersList>
                                <xsl:sequence select="$var26_let" />
                            </SalesHeadersList>
                        </xsl:variable>
                        <xsl:for-each select="$var17_create_SalesHeadersList/ShipCancelDate">
                            <ShipCancelDate>
                                <xsl:sequence select="fn:string(.)" />
                            </ShipCancelDate>
                        </xsl:for-each>
                        <xsl:for-each select="current-group()">
                            <SalesLinesList>
                                <xsl:for-each select="CustomersLineNumber">
                                    <CustomersLineNumber>
                                        <xsl:sequence select="fn:string(.)" />
                                    </CustomersLineNumber>
                                </xsl:for-each>
                                <xsl:for-each select="ItemNumber">
                                    <ItemNumber>
                                        <xsl:sequence select="fn:string(.)" />
                                    </ItemNumber>
                                </xsl:for-each>
                                <xsl:for-each select="RequestedReceiptDate">
                                    <RequestedReceiptDate>
                                        <xsl:sequence select="fn:string(.)" />
                                    </RequestedReceiptDate>
                                </xsl:for-each>
                                <xsl:for-each select="SalesPrice">
                                    <SalesPrice>
                                        <xsl:sequence select="fn:string(.)" />
                                    </SalesPrice>
                                </xsl:for-each>
                                <xsl:for-each select="DefaultDimension/Values/Value">
                                    <xsl:variable name="var18_cur" as="node()" select="." />
                                    <xsl:for-each select="(./Value)[fn:exists(($var18_cur/Name)[(fn:string(.) = $var19_resultof_grouping_key)])]">
                                        <OrderedSalesQuantity>
                                            <xsl:sequence select="fn:string(.)" />
                                        </OrderedSalesQuantity>
                                    </xsl:for-each>
                                </xsl:for-each>
                                <xsl:for-each select="SalesUnitSymbol">
                                    <SalesUnitSymbol>
                                        <xsl:sequence select="fn:string(.)" />
                                    </SalesUnitSymbol>
                                </xsl:for-each>
                                <xsl:for-each select="RequestedShippingDate">
                                    <RequestedShippingDate>
                                        <xsl:sequence select="fn:string(.)" />
                                    </RequestedShippingDate>
                                </xsl:for-each>
                                <xsl:for-each select="ProductColorId">
                                    <ProductColorId>
                                        <xsl:sequence select="fn:string(.)" />
                                    </ProductColorId>
                                </xsl:for-each>
                                <xsl:for-each select="ProductStyleId">
                                    <ProductStyleId>
                                        <xsl:sequence select="fn:string(.)" />
                                    </ProductStyleId>
                                </xsl:for-each>
                                <xsl:for-each select="BarCode">
                                    <BarCode>
                                        <xsl:sequence select="fn:string(.)" />
                                    </BarCode>
                                </xsl:for-each>
                            </SalesLinesList>
                        </xsl:for-each>
                    </SalesHeadersList>
                </xsl:for-each-group>
                <xsl:variable name="var20_create_SalesHeadersList" as="node()">
                    <SalesHeadersList>
                        <xsl:sequence select="$var26_let" />
                    </SalesHeadersList>
                </xsl:variable>
                <xsl:if test="fn:not(fn:exists(($var20_create_SalesHeadersList/SalesLinesList)[fn:exists((./DefaultDimension)[fn:exists((./Values)[fn:exists(Value)])])]))">
                    <SalesHeadersList>
                        <xsl:sequence select="($var20_create_SalesHeadersList/@node(), $var20_create_SalesHeadersList/node())" />
                    </SalesHeadersList>
                </xsl:if>
                <SalesHeadersList>
                    <xsl:sequence select="()" />
                </SalesHeadersList>
            </xsl:for-each>
        </_salesOrder>
    </xsl:template>
</xsl:stylesheet>